version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
       - ./initdb:/docker-entrypoint-initdb.d
